// <auto-generated />
using Dsw2026Tpi.Data;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Dsw2026Tpi.Data.Migrations.Domain
{
    [DbContext(typeof(Dsw2026TpiDbContext))]
    [Migration("20260803150000_AddDoctorDeletedSoftDelete")]
    partial class AddDoctorDeletedSoftDelete
    {
    }
}
